import os
import json
import urllib.request
import signal

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "gemma4:e4b"

def review_code_with_ollama(file_path, content):
    prompt = f"""
Please act as an expert iOS Developer and Code Reviewer.
I am reviewing the RentiWise codebase (a Swift/iOS app) before TestFlight release.
Review the following Swift file '{file_path}'.
Identify any potential logic bugs, retain cycles, security issues, UI threading issues, or performance bottlenecks.
Provide actionable recommendations on architecture or best practices.

File Content:
```swift
{content}
```
"""
    
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.2
        }
    }
    
    try:
        # Added timeout to prevent infinite blocking
        req = urllib.request.Request(OLLAMA_URL, data=json.dumps(payload).encode('utf-8'), headers={'Content-Type': 'application/json'})
        with urllib.request.urlopen(req, timeout=120) as response:
            result = json.loads(response.read().decode('utf-8'))
            return result.get("response", "No response from model.")
    except Exception as e:
        return f"Error connecting to Ollama: {str(e)}"

def main():
    target_dir = "RentiWise"
    
    # Files carefully selected for review
    selected_files = [
        "RentiWise/AppDelegate.swift",
        "RentiWise/Features/Verification/PhoneVerificationService.swift",
        "RentiWise/Features/Verification/CollegeVerificationService.swift",
        "RentiWise/Features/Add item/ViewController/AddItemPublishViewController.swift",
        "RentiWise/Features/IAP/IAPManager.swift"
    ]
    
    output_file = "codebase_review_results.md"
    
    # Initialize the report file
    with open(output_file, "w") as f:
        f.write("# RentiWise Codebase Review & Recommendations\n\n")
        f.write("> [!NOTE]\n> The codebase built successfully without errors (`** BUILD SUCCEEDED **`). The following review was generated by Gemma 4 (via Ollama) focusing on potential logic flaws, architecture recommendations, and best practices before TestFlight deployment.\n\n")

    print(f"Total Swift files for review: {len(selected_files)}.")
    
    for i, filepath in enumerate(selected_files):
        print(f"[{i+1}/{len(selected_files)}] Reviewing {filepath}...")
        
        if not os.path.exists(filepath):
            print(f"File {filepath} not found. Skipping.")
            continue
            
        with open(filepath, "r") as f:
            content = f.read()
            
        review = review_code_with_ollama(filepath, content)
        
        # Append immediately to save progress in case of crash
        with open(output_file, "a") as f:
            f.write(f"## File: `{filepath}`\n\n{review}\n\n---\n\n")
        print(f"-> Saved review for {filepath}")

    print(f"Process finished! Results saved to {output_file}.")

if __name__ == "__main__":
    main()
